// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

package main

import (
	"flag"
	"fmt"
	"github.com/sjclijie/go-zero/core/conf"
	"github.com/sjclijie/go-zero/core/logx"
	"github.com/sjclijie/go-zero/core/proc"
	"github.com/sjclijie/go-zero/zrpc"

	"bookstore/rpc/add/add"
	"bookstore/rpc/add/internal/config"
	"bookstore/rpc/add/internal/server"
	"bookstore/rpc/add/internal/svc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/add.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewAdderServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		add.RegisterAdderServer(grpcServer, srv)
	})
	defer s.Stop()

	waitForCalled := proc.AddShutdownListener(func() {
		logx.Infof("%s is down...", c.Name)
	})
	defer waitForCalled()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
