// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	book "bookstore/api/internal/handler/book"
	"bookstore/api/internal/svc"

	"github.com/sjclijie/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/add",
					Handler: book.AddHandler(serverCtx),
				},
			}...,
		),
	)
}
